In [19]:
import soccerdata as sd
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

## Data Scraping

Premier league data after VAR introduced i.e past 2018 season.

In [20]:
premier_league = sd.Understat(leagues="ENG-Premier League", 
                              seasons=["2019/2020", "2020/2021", "2021/2022", "2022/2023", "2023/2024", "2024/2025", "2025/2026"])

[10/17/26 13:47:55] INFO     Saving cached data to C:\Users\ATHARV\soccerdata\data\Understat         ]8;id=6119234;file://d:\coding\xG_predict\.venv\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=6119235;file://d:\coding\xG_predict\.venv\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

In [21]:
shots = premier_league.read_shot_events()
shots.head()

                                                                                  league_id  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson         1
                                                                 Andrew Robertson         1
                                                                 Divock Origi             1
                                                                 Fabinho                  1
                                                                 Jordan Henderson         1

                                                                                   season_id  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson       2019
                                                                 Andrew Robertson       2019
                                                                 Divock Origi           2019
                                                                 Fabinho                2019
                                                                 Jordan Henderson       2019

                                                                                   game_id  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson    11643
                                                                 Andrew Robertson    11643
                                                                 Divock Origi        11643
                                                                 Fabinho             11643
                                                                 Jordan Henderson    11643

                                                                                                 date  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson 2019-08-09 20:00:00
                                                                 Andrew Robertson 2019-08-09 20:00:00
                                                                 Divock Origi     2019-08-09 20:00:00
                                                                 Fabinho          2019-08-09 20:00:00
                                                                 Jordan Henderson 2019-08-09 20:00:00

                                                                                   shot_id  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson   309897
                                                                 Andrew Robertson   309911
                                                                 Divock Origi       309904
                                                                 Fabinho            309910
                                                                 Jordan Henderson   309906

                                                                                   team_id  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson       87
                                                                 Andrew Robertson       87
                                                                 Divock Origi           87
                                                                 Fabinho                87
                                                                 Jordan Henderson       87

                                                                                   player_id  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson       1688
                                                                 Andrew Robertson       1688
                                                                 Divock Origi            484
                                                                 Fabinho                3420
                                                                 Jordan Henderson        605

                                                                                   assist_player_id  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson            341162
                                                                 Andrew Robertson              <NA>
                                                                 Divock Origi                341153
                                                                 Fabinho                       <NA>
                                                                 Jordan Henderson            341162

                                                                                            assist_player  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson            Divock Origi
                                                                 Andrew Robertson                    <NA>
                                                                 Divock Origi      Trent Alexander-Arnold
                                                                 Fabinho                             <NA>
                                                                 Jordan Henderson            Divock Origi

                                                                                         xg  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson  0.053779
                                                                 Andrew Robertson  0.013076
                                                                 Divock Origi      0.258252
                                                                 Fabinho           0.014726
                                                                 Jordan Henderson  0.126691

                                                                                   location_x  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson       0.883
                                                                 Andrew Robertson        0.78
                                                                 Divock Origi           0.891
                                                                 Fabinho                0.727
                                                                 Jordan Henderson       0.875

                                                                                   location_y  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson       0.713
                                                                 Andrew Robertson       0.693
                                                                 Divock Origi            0.53
                                                                 Fabinho                0.536
                                                                 Jordan Henderson        0.53

                                                                                   minute  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson      15
                                                                 Andrew Robertson      57
                                                                 Divock Origi          41
                                                                 Fabinho               54
                                                                 Jordan Henderson      47

                                                                                    body_part  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson   Left Foot
                                                                 Andrew Robertson   Left Foot
                                                                 Divock Origi            <NA>
                                                                 Fabinho           Right Foot
                                                                 Jordan Henderson  Right Foot

                                                                                   situation  \
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson  Open Play
                                                                 Andrew Robertson  Set Piece
                                                                 Divock Origi      Open Play
                                                                 Fabinho           Open Play
                                                                 Jordan Henderson  Open Play

                                                                                        result
league             season game                         team      player
ENG-Premier League 1920   2019-08-09 Liverpool-Norwich Liverpool Andrew Robertson  Missed Shot
                                                                 Andrew Robertson  Missed Shot
                                                                 Divock Origi             Goal
                                                                 Fabinho            Saved Shot
                                                                 Jordan Henderson   Saved Shot

As we got the overall dataset of shots attempted in each match of premier league from season 2019 til 2025 which is the `VAR era` from `Understat` api using `soccerdata` package/sdk.

In [22]:
shots.info()

<class 'pandas.DataFrame'>
MultiIndex: 68007 entries, ('ENG-Premier League', '1920', '2019-08-09 Liverpool-Norwich', 'Liverpool', 'Andrew Robertson') to ('ENG-Premier League', '2526', '2026-05-24 West Ham-Leeds', 'West Ham', 'Valentín Castellanos')
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league_id         68007 non-null  string
 1   season_id         68007 non-null  Int64
 2   game_id           68007 non-null  Int64
 3   date              68007 non-null  datetime64[us]
 4   shot_id           68007 non-null  Int64
 5   team_id           68007 non-null  Int64
 6   player_id         68007 non-null  Int64
 7   assist_player_id  50123 non-null  Int64
 8   assist_player     50123 non-null  string
 9   xg                68007 non-null  Float64
 10  location_x        68007 non-null  Float64
 11  location_y        68007 non-null  Float64
 12  minute            68007 non-null  Int64
 13  body_part         55888 non-null  string
 14  situation         67306 non-null  string
 15  result            68007 non-null  string
dtypes: Float64(3), Int64(7), datetime64[us](1), string(5)
memory usage: 9.4+ MB

In [23]:
goals = shots[shots["result"] == 'Goal']
goals.info()

<class 'pandas.DataFrame'>
MultiIndex: 7343 entries, ('ENG-Premier League', '1920', '2019-08-09 Liverpool-Norwich', 'Liverpool', 'Divock Origi') to ('ENG-Premier League', '2526', '2026-05-24 West Ham-Leeds', 'West Ham', 'Valentín Castellanos')
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league_id         7343 non-null   string
 1   season_id         7343 non-null   Int64
 2   game_id           7343 non-null   Int64
 3   date              7343 non-null   datetime64[us]
 4   shot_id           7343 non-null   Int64
 5   team_id           7343 non-null   Int64
 6   player_id         7343 non-null   Int64
 7   assist_player_id  5198 non-null   Int64
 8   assist_player     5198 non-null   string
 9   xg                7343 non-null   Float64
 10  location_x        7343 non-null   Float64
 11  location_y        7343 non-null   Float64
 12  minute            7343 non-null   Int64
 13  body_part         6104 non-null   string
 14  situation         6769 non-null   string
 15  result            7343 non-null   string
dtypes: Float64(3), Int64(7), datetime64[us](1), string(5)
memory usage: 1.0+ MB

So total of 68007 shots only 7343 resulted in a goal.

In [24]:
#X = pd.DataFrame(index=None)
#X["location_x"] = shots["location_x"]
#X["location_y"] = shots["location_y"]
#X["body_part"] = shots["body_part"]
#X["situation"] = shots["situation"]
cols=["location_x", "location_y", "body_part", "situation"]
X=shots[cols].copy()
X.info()

<class 'pandas.DataFrame'>
MultiIndex: 68007 entries, ('ENG-Premier League', '1920', '2019-08-09 Liverpool-Norwich', 'Liverpool', 'Andrew Robertson') to ('ENG-Premier League', '2526', '2026-05-24 West Ham-Leeds', 'West Ham', 'Valentín Castellanos')
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location_x  68007 non-null  Float64
 1   location_y  68007 non-null  Float64
 2   body_part   55888 non-null  string
 3   situation   67306 non-null  string
dtypes: Float64(2), string(2)
memory usage: 2.7+ MB

In [25]:
X = X.reset_index(drop=True)

In [26]:
X.head(10)

   location_x  location_y   body_part  situation
0       0.883       0.713   Left Foot  Open Play
1        0.78       0.693   Left Foot  Set Piece
2       0.891        0.53        <NA>  Open Play
3       0.727       0.536  Right Foot  Open Play
4       0.875        0.53  Right Foot  Open Play
5       0.849       0.418  Right Foot  Open Play
6       0.933       0.367   Left Foot  Open Play
7        0.88       0.339   Left Foot  Open Play
8       0.878       0.555   Left Foot  Open Play
9       0.848       0.694   Left Foot  Open Play

In [27]:
y = pd.Series(np.where(shots["result"]=="Goal", 1, 0))
y.head()

0    0
1    0
2    1
3    0
4    0
dtype: int64

As we got the dataset `X` and label `y` we can start with inspection `{EDA}` of the dataset. We arent direectly training againt the giiven`xg` but we will predict the probability of the shot whether it will end up in goal or not, as it is the actual definition of the `xG`

In [28]:
X.to_csv("../dataset/dataset.csv", index=False)
y.to_csv("../dataset/label.csv", index=False)

Saving the dataset and labels so it can be utilised allover the repo.